### ISSUE TITLE
[Feature]: Add React 18 support for `react-live-runner`

### ISSUE THREAD

**Issue by sabertazimi** [nihgwu/react-runner#123]
## **Is your feature request related to a problem? Please describe.**

Last npm release from `react-simple-code-editor` is `v0.11.0`, almost 2 years ago.
It's better to replace it with another React code editor that supports React 18.

## **Describe the solution you'd like**

Replace `react-simple-code-editor`.

**Comment by nihgwu** [comment]
I've tried other solutions, like `use-editable`, but I'd say `react-simple-code-editor` provides the best UX and less bugs, I don't think there is anything preventing it's been used with React 18, just ignore the warnings for now, and `react-live-runner` aims to provide a smooth transition from `react-live`, if you want to use other code editors, you are free to use theme with `react-runner`, like `CodeMirror`, `CodeJar` or even `Monaco`, I don't have the bandwidth to maintain another editor which is complicated regarding multi browsers support

**Comment by sabertazimi** [comment]
Thx for replying

**Comment by sabertazimi** [comment]
[React simple code editor](https://github.com/react-simple-code-editor/react-simple-code-editor) has shipped to TypeScript
and updated its peerDependencies. It's time to upgrade.
