### ISSUE TITLE
Only trap focus when content has been edited

### ISSUE THREAD

**Issue by mbrookes** [nihgwu/react-runner#124]
Jarle provides a nice accessibility/usability feature that allows to tab past the editor in a natural way, without having to first hit Esc.
https://jquense.github.io/jarle/#accessiblity

It would be good to see the same feature in react-runner.

**Comment by nihgwu** [comment]
see https://github.com/mui/material-ui/pull/32107#issuecomment-1130503831

It's nothing to do with `react-runner`, and the code editor is in `react-live-runner` which is aimed to provide a smooth transition from `react-live`, so if you need advanced features, you are free you use any editor with `react-runner`, also see https://github.com/nihgwu/react-runner/issues/123#issuecomment-1120427135
