### ISSUE TITLE
multi files jsx with css is supported ?

### ISSUE THREAD

**Issue by c0ncentus** [nihgwu/react-runner#131]
hi, 
multi files with css is supported ?

**Comment by nihgwu** [comment]
Sure, see [this example](https://play-react.vercel.app/#N4IgggDhB0AuDOAPEAuEBLAthA9gJ1gAJhCBXeAUwGVYBDWCwgX0IDM8dNCByPC2gMaxuAHQB2WXAWKEAQjlp4AJszYcu3aAHp5ipdABW8UWPEVEUokoqtapADZFWpMUPQ4xhAOK1MFABQAlMTihIQCHvBEANoAFuhR+ACeADSElLAAEgmwyQC6hAC8ZJQ09AHRYHh4tEn+AJyB0Kzo9vb+Yg72gXmBoeGRMVEUEABypJgARhR4aRk0I+NTMwXF5NR0DP4ADH2eA2JRhIgAkvCj5kTFw2MT03iEAKSEAExFhcXb-RGHRAKk1QoYlgVAAjqRFBR4EVCPFEngktEbkt7nlxP1nK5YO5PLFaGIlPYKAAFey1DoUADuYIhfHgwWA-TCRKIYip2XhSRhcNyCOg8Hs6AEAW2cwYt2WDwA1IQAIxNH4Cej+aJs6ngyHwXpM9IULI5ZIUykc3lJPZhMLzcUomZGk3JaBEsQAc1gsUIAFo5ebmOj9pi3B5CAYJhAACo4fw3Bk6q2LO626P9Jh+sI-I6YHAANyh3INfMwtAg-ij4rSmZzwUKAD4Qvs04NCNZ4AI8OgINig8UK4xa9tCAB+QgAAy8OEIuUIPcIAGIACTAHtMYeEFA8McT8fO3yMKKKYQ6viwAGefw6sIAHkFhAA1hQkoVF9mKExq+eLRfJqRYLlPB4AMKCgIN6PkERS1iG2ARv4PaBK+wDNq27admITAXloX4-h4b71h+WiCjhFqED6TB7P0R4noQZ64ReSjoFm4RkvA5w7oUIggNufjsYRRGELR9GMbQzGjKx7GcRQHqTAoyjce+l66MoxxnBciCwI+pznJcLDwBqdKPv8gLAjSmosB4pK1I+eIEkS5lJCwWg8UR6F0Vmjkfi5gnCaJHE7h66BiKwOCybhTk4PY1ZPjm8BoVoYVuZeWguW5zn0TxewpmIIApCACn6EYqAYNg+BECQSr2P8ZIMAA6v5bIPCw7CcDw2jfq08CGMYfoBihhDGXw-gkFmtD2KQFBpABQE3swMb7BReCnjqn7fr+nksX4bEgDptIUOxhATUKIHAGBNZ7WIgEHUEr7vsAQ0jS+i0Yct2H9OlfrmJYbAuIGni5QNSmaapcy6VC41iLZ011mE3U4rC+KEhQ53Af46AzUR6CsFRZUVeUNViHVUbA-ShAAD7E+khPROgvSQ7xc2mLhGVEemrJUn1ubXIT-JAQEPphGqbPwJTqz-SpRBDtwAAa3CrjwADyJhEWZZJ1PzhMkamn1YjDfAEjMbPI6jFp03xbOELdo2PltmpC6ZZ2TaBVa1lZ8OIzeBv2TxGXfI2lK1TMMJYw4ON+3gBPbfS-QsukmzkP06NUb7eMzIblox9CxTcLjdVrtLMqJ3VyaEBQ9iUDTqf0OQMLcKLhAQMrMw54QMr+BpNfi1LMvcPL6v02ExvUU5SXvvxDECExa0UBte7HvA3HANP5AxUPIV8R5Y9CRPG1SXoHocJSwW8RawA69YeD67sjOH8QJ968D-jypfh-H0Cp-6y8cHD4lqXD2v48iet7Ft7KF3jgfeIB4pHxvmfO+ABmD+K8wjP11tA7a-gAAs8Cr7XxfrfVBABWTBvEUquR-gJdeXkAEgCAUoEBYCIGIKgfrAAbIQp+jC74AHZWG8SQa-O+AAObhCVl5OS-iQ-Yr1MrZVaiXDqBV3rFU1t9cIw1sbVRDmHTUhtmaEEFGydOhBog6miKKOUaQXh5BSMYmBaQ0FpDwZY4xTC0gcLSPwxxuETFpBsYQJhHiiLRFlLYlx-iLTRBePYtxoSwheMIHYwg7irGeIiXEtIfiklhDRP6fAVEo7oBhNsAA3IQfJF5dH+ShI6IErpYjFPQFKKUKcDhHGiLQNIkw0gCGFnoqEQsdTx00XSVpBQABkIzybh2Ge8DmkzJijPGVbIZtBVgfAmdbLpTS+56koos3pyydSX0vsbTobRxAZSyptWASQiTQAEMxAqUklBckZNk4Ea5ZRoIgIgHg-4gTHgRN4HAbohTcDSAAMW-ACNp6R8TwA9JQNsrBCn9AgLQJQdEXRrheNsL5yLUJ+jCkkhwNNUXov8s6D0RJWCwDXDAnFiA8VezENAahtCUC0Gpf7F5aYiSKDXFJN0eKGzAj+TnbgQqmwJDrrUNcdBJhEkZX6fkacaaFjwM6fykkgW5EwO8+lir6b8mBjTKSygG5yi+ekMK6AVAznqPaiVrB7AKBpbomwsBHUeFgPC9AAAvCgWLPkMoxF6j0lIKDoGdLEV1Ul7BKAlT0j0sQI1RtdTAoNErk2RujbSjN-Q1UarELvbNrqPSylxfmxQhaPS5AgGuMtFb9ikoxc6NcRT+gMFUh6YakaxBrmFCKvAErfZKDdLmxtTKjXbRQIFf40JuV7W-D0tcYgPAUANeIaAN5Jg0LELQLMkb6AwynZCGdOA50msEDeZ0HAXBKDXDOdF8azlKvEjTOi8BpVJDXE68wjqiSIA9HRPg301x7w3cy8SfkArjgXQWzVVLXXYoneIEATAgA) or [this one](https://react-runner.vercel.app/#multi-files), it's just about how to apply styles, you can use ShadowDom with [constructive stylesheet](https://github.com/calebdwilliams/construct-style-sheets)
