### ISSUE TITLE
Is this library maitained?

### ISSUE THREAD

**Issue by diyorbek** [nihgwu/react-runner#171]
I am curious if the library is still maintained. There seems to be no response from the author for the open issues and PRs.

**Comment by nihgwu** [comment]
Thanks for reminding, I think I missed some issue reports 😄 
Regarding PR, there is only one experimental PR which I don't think will be landed, the rest are just deps update
the lib itself is pretty stable, that's why I didn't push any changes for a long time, at least I use it everyday

**Comment by diyorbek** [comment]
@nihgwu Oh, that's great. Happy that the project is not abandoned :D . Thank you so much!
