### ISSUE TITLE
Async transform/transpile

### ISSUE THREAD

**Issue by Andarist** [nihgwu/react-runner#95]
It would be cool if it would be possible to handle transforming/transpilation in an async manner and to provide a build with which this could be utilized without bundling the transpiler at the same time (i’d like to move the transpilation to a webworker, so i dont need Sucrase to be included in the main bundle)

**Comment by nihgwu** [comment]
@Andarist regarding the worker I replied [here](https://github.com/emotion-js/emotion/pull/2571#issuecomment-1008321154), but yes I agree it would be nice to support custom transpiler, for example using babel for better error message, for now we can alias the import like `alias: { sucrase: '../yourCustomTranspiler' }` to achieve that

The problem with webworker is that it doesn't support SSR (probably we can support that for the first rendering), and from my experience, sucrase is fast enough to ignore the impact of transpilation 

For custom async transpiling, I replied [here](https://github.com/emotion-js/emotion/pull/2571#issuecomment-1008454923)

> TBH it makes no sense to use `react-live` or other similar solutions at all if you use babel-standalone to compile your code as in that case you can just use it to compile the whole code without `buble`, and then `new Function(...)`, that's all, then you are free to use anything

**Comment by Andarist** [comment]
I'll try to test Sucrase more but at least with Buble i could notice minor delays when typing fast when the transpilation has happened on each keystroke (i dont think that debouncing fixes this, it only helps to hide the issue as it occurs less often)

**Comment by nihgwu** [comment]
@Andarist you can try [this deploy](https://react-runner-git-neo-emotion-neonie.vercel.app/playground) from #63 which supports Emotion

**Comment by Andarist** [comment]
I think I can *occasionally* see a slower keystroke - it's not that easy to see it though. However, in the recorded profiling session I can see some tasks taking over the 16ms budget. The longest one was 100ms, although I'm willing to believe that it was related to something else as I can't see a similar stack trace among other tasks. I see some 50ms tasks related to the keypress events but it's hard to quickly tell if Sucrase is actually slowing this down is it just because of React itself (I'm somewhat inclined to say that it's the latter here though).

When bashing my keys or when testing with CPU throttling I can definitely see slowdowns but it seems that it's mostly related to React. A somewhat funny thing is that if I enable CPU throttling on https://sucrase.io/ then I can also definitely see slowdowns but the reported transpilation times are rather constant (regardless of the CPU throttling factor). I find it somewhat strange but perhaps it's just that optimized that the CPU throttling doesn't matter that much for it and it only slows down other parts of the code.

And hah - I see that we've already crossed our paths in that Emotion's PR. 😅 Nice to see you again. I think that I somewhat got convinced here that this lib is solid and the perf is good too so we can revisit using it on Emotion's site

**Comment by nihgwu** [comment]
@Andarist regarding the Emotion doc website, I'm happy to create a PR there to try it out, or should we do it right [here](https://github.com/emotion-js/emotion/pull/2571)?
